# Generated by Django 5.2.4 on 2025-08-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_invoice_outstanding_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
