# Generated by Django 4.2.7 on 2025-10-15 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_inventory_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_invoice_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='last_notified_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='last_stock_check',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price_drop_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='stock_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='was_in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reserved_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_locked', models.BooleanField(default=False)),
                ('notify_when_available', models.BooleanField(default=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('expected_availability', models.DateTimeField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_orders', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pre_orders',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['status', 'product'], name='pre_orders_status_6ea411_idx'), models.Index(fields=['user', 'status'], name='pre_orders_user_id_e83123_idx'), models.Index(fields=['expires_at'], name='pre_orders_expires_6da861_idx')],
            },
        ),
    ]
