# Generated by Django 5.2.4 on 2025-07-25 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrating',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrating',
            name='delivery_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='deliveries.deliveryrequest'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='delivery_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_locations', to='deliveries.deliveryrequest'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverschedule',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='driverschedule',
            unique_together={('driver', 'date')},
        ),
    ]
