# Generated by Django 5.2.4 on 2025-07-27 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productimage_image_url_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProductMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(choices=[('piece', 'Piece'), ('pair', 'Pair'), ('dozen', 'Dozen'), ('half_dozen', 'Half Dozen'), ('box', 'Box'), ('carton', 'Carton'), ('pack', 'Pack'), ('bundle', 'Bundle'), ('set', 'Set'), ('case', 'Case'), ('tray', 'Tray'), ('roll', 'Roll'), ('bottle', 'Bottle'), ('can', 'Can'), ('tin', 'Tin'), ('barrel', 'Barrel'), ('drum', 'Drum'), ('sack', 'Sack'), ('bag', 'Bag'), ('jar', 'Jar'), ('tube', 'Tube'), ('strip', 'Strip'), ('kit', 'Kit'), ('shot', 'Shot (30ml or 1oz)'), ('nip', 'Nip (50ml)'), ('quarter', 'Quarter (180ml)'), ('half', 'Half (375ml)'), ('pint', 'Pint (473ml / 500ml)'), ('fifth', 'Fifth (750ml)'), ('liter', 'Liter (1000ml)'), ('gallon', 'Gallon (3.78L)'), ('keg', 'Keg (varies, e.g., 20L, 30L, 50L)'), ('jug', 'Jug'), ('flask', 'Flask'), ('tumbler', 'Tumbler (glass)'), ('mug', 'Mug'), ('cup', 'Cup'), ('glass', 'Glass'), ('crate', 'Crate (collection of bottles or cans)'), ('box_wine', 'Box Wine (e.g., 3L, 5L)')], max_length=50)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='products.product')),
            ],
            options={
                'db_table': 'product_measurements',
                'ordering': ['sort_order', 'price'],
                'unique_together': {('product', 'measurement', 'quantity')},
            },
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productmeasurement'),
        ),
    ]
