# Generated by Django 5.2.4 on 2025-07-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price_alter_product_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmeasurement',
            name='stock',
        ),
    ]
