# Generated by Django 5.2.4 on 2025-07-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_stock_from_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeasurement',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
