# Generated by Django 4.2.7 on 2025-10-15 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_change_quantity_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0)),
                ('reserved_stock', models.IntegerField(default=0)),
                ('available_stock', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=10)),
                ('max_stock_level', models.IntegerField(default=1000)),
                ('reorder_point', models.IntegerField(default=20)),
                ('reorder_quantity', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_backorders', models.BooleanField(default=False)),
                ('track_quantity', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_stock_check', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase/Receiving'), ('sale', 'Sale'), ('adjustment', 'Stock Adjustment'), ('damage', 'Damage/Loss'), ('return', 'Customer Return'), ('transfer', 'Transfer Between Locations'), ('reservation', 'Stock Reservation'), ('release', 'Reservation Release'), ('restock', 'Restock'), ('expired', 'Expired Stock Removal')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.inventoryitem')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory_item', 'movement_type'], name='stock_movem_invento_a7cbeb_idx'), models.Index(fields=['created_at'], name='stock_movem_created_07bdcc_idx'), models.Index(fields=['reference'], name='stock_movem_referen_de2378_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['current_stock', 'min_stock_level'], name='inventory_i_current_888972_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['available_stock'], name='inventory_i_availab_657a96_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['last_updated'], name='inventory_i_last_up_7ab20a_idx'),
        ),
    ]
