# Generated by Django 5.2.4 on 2025-07-25 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('new_deliveries', models.IntegerField(default=0)),
                ('completed_deliveries', models.IntegerField(default=0)),
                ('cancelled_deliveries', models.IntegerField(default=0)),
                ('avg_delivery_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_delivery_distance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_delivery_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('active_drivers', models.IntegerField(default=0)),
                ('avg_driver_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('new_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_payments', models.IntegerField(default=0)),
                ('card_payments', models.IntegerField(default=0)),
                ('mobile_money_payments', models.IntegerField(default=0)),
                ('wallet_payments', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('unique_views', models.IntegerField(default=0)),
                ('add_to_cart_count', models.IntegerField(default=0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_reviews', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revenue_growth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order_growth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'revenue_metrics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.IntegerField(default=0)),
                ('clicked_results', models.JSONField(blank=True, default=list)),
                ('search_time', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('category_filter', models.CharField(blank=True, max_length=100, null=True)),
                ('price_filter', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'search_analytics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('returning_users', models.IntegerField(default=0)),
                ('customers', models.IntegerField(default=0)),
                ('drivers', models.IntegerField(default=0)),
                ('admins', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('avg_session_duration', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_signup', 'User Signup'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('profile_update', 'Profile Update'), ('product_view', 'Product View'), ('product_search', 'Product Search'), ('product_add_to_cart', 'Product Added to Cart'), ('product_remove_from_cart', 'Product Removed from Cart'), ('product_purchase', 'Product Purchase'), ('product_review', 'Product Review'), ('order_created', 'Order Created'), ('order_confirmed', 'Order Confirmed'), ('order_cancelled', 'Order Cancelled'), ('order_delivered', 'Order Delivered'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('delivery_requested', 'Delivery Requested'), ('delivery_accepted', 'Delivery Accepted'), ('delivery_picked_up', 'Delivery Picked Up'), ('delivery_delivered', 'Delivery Delivered'), ('delivery_cancelled', 'Delivery Cancelled'), ('app_open', 'App Open'), ('app_close', 'App Close'), ('page_view', 'Page View'), ('button_click', 'Button Click')], max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
