# Generated by Django 5.2.4 on 2025-07-25 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmetrics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='revenuemetrics',
            unique_together={('period_type', 'period_start', 'period_end')},
        ),
        migrations.AddField(
            model_name='searchanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_c3dcde_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'created_at'], name='analytics_e_user_id_7e4ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_id', 'created_at'], name='analytics_e_session_283fe0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productmetrics',
            unique_together={('date', 'product')},
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['query', 'created_at'], name='search_anal_query_2667a1_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['user', 'created_at'], name='search_anal_user_id_5f3483_idx'),
        ),
    ]
