# Generated by Django 5.2.4 on 2025-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('ussd', 'USSD'), ('qr', 'QR Code'), ('barter', 'Barter'), ('mpesa', 'M-Pesa'), ('gh_mo_mo', 'Ghana Mobile Money'), ('ug_mo_mo', 'Uganda Mobile Money'), ('franc_mo_mo', 'Francophone Mobile Money'), ('emz_mo_mo', 'EMZ Mobile Money'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('payattitude', 'PayAttitude'), ('cash', 'Cash Payment')], max_length=20),
        ),
    ]
