# Generated by Django 5.2.4 on 2025-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='idempotency_cache_hit',
            field=models.BooleanField(default=False),
        ),
    ]
