# Generated by Django 5.2.4 on 2025-08-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymenttransaction_idempotency_cache_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='flutterwave_charge_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='flutterwave_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='flutterwave_payment_method_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
