# Generated by Django 4.2.7 on 2025-10-15 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0006_paymentreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='country_code',
            field=models.CharField(default='UG', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='User-friendly name for this payment method', max_length=100)),
                ('method_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer'), ('wallet', 'BottlePlug Wallet')], max_length=20)),
                ('method_data', models.JSONField(help_text='Encrypted payment method details')),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default payment method")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this payment method was last used', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_payment_methods',
                'ordering': ['-is_default', '-last_used_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_paymen_user_id_6b2aae_idx'), models.Index(fields=['user', 'is_default'], name='user_paymen_user_id_4cb5ec_idx')],
                'unique_together': {('user', 'nickname')},
            },
        ),
    ]
