# Generated by Django 5.2.4 on 2025-07-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # firebase_uid field already exists in 0001_initial.py, so this migration is not needed
        # Keeping empty operations to maintain migration history
    ]
