# Generated by Django 5.2.4 on 2025-07-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_date_of_birth_user_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_worker',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
