# Generated by Django 4.2.7 on 2025-08-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
    ]
