# Generated by Django 4.2.7 on 2025-10-15 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_payment_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_worker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='user',
            name='push_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_addresses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_deliveries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="User's bio or description", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
